language: r

warnings_are_errors: true

apt_packages:
  - libcurl4-openssl-dev
  - npm
  - git

before_install:
  - ( cd .. ; clone https://github.com/maxogden/dat; cd dat; npm install; npm link )

r_github_packages:
 - jeroenooms/curl
 - jeroenooms/jsonlite

notifications:
  email:
    on_success: change
    on_failure: change
